version: "3.9"

services:
  fetweb:
    image: fetweb-link:0.1
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fetweb-linkador
    ports:
      - "8000:8000"
    command: ["python", "Index.py"]
